### ISSUE TITLE
No message on <discovery_prefix> when wink-mqtt-rs starts

### ISSUE THREAD

**Issue by froohoo** [mikekap/wink-mqtt-rs#34]
Thanks for putting this together. IMO the Wink-1 hardware itself is great and I'm glad you are giving it a second life.

I'm in the process of setting it up with Home Assistant, and I've run into an issue where I don't see anything sent to the mqtt broker on homeassistant/, either when I reboot the wink or restart the service. I'm seeing the mqtt traffic from the wink both in HA and in MQTT explorer, but nothing on homeassistant/. I can manually publish a message to homeassistant/status and that shows up, but I never get one from wink-mqtt-rs

Config:
```
-s mqtt://hamqtt:*************@192.168.1.111
-d homeassistant
```
![image](https://user-images.githubusercontent.com/23066079/107129067-74d6b080-6888-11eb-985f-18238478b149.png)

**Comment by mikekap** [comment]
Sorry for the late response here. Are there any log entries from `/var/log/wink-mqtt-rs.log`? You should see some lines that either say `discovered_device` or `unknown_device`. 

If you do have lines with `unknown_device`, could you include the output of `aprontest -l` and `aprontest -l -m 6` (the others are useful too if there are multiple "types" of devices connected to your wink)?

If you don't have any of those lines - could you add `-v` to your config file? It should increase the logging verbosity to get some more info as to what might be going wrong.

**Comment by froohoo** [comment]
Thanks Mike, Here is what I get when the log starts up (with verbose logging enabled)

Nodes 2 & 5 are both GE Quirky zigbee window sensors that I don't really use anymore. 

`Mar 08 21:24:32.154 INFO init_logger, min_log_level: Debug
Mar 08 21:24:32.157 INFO starting, version: 0.2.0
Mar 08 21:24:32.274 INFO opening_client, client_id: wink-mqtt-rs, port: 1883, host: 192.168.1.111
Mar 08 21:24:32.299 INFO poller_starting, resync_interval: 10000
Mar 08 21:24:32.309 INFO started_http_server, listen_addr: 0.0.0.0:3000
Mar 08 21:24:32.327 DEBG running_command, cmd: aprontest -l
Mar 08 21:24:32.603 DEBG running_command, cmd: aprontest -l -m 2
Mar 08 21:24:32.972 WARN poll_device_failed, error: SimpleError { err: "Bad attribute type: UINT64" }
Mar 08 21:24:33.005 DEBG running_command, cmd: aprontest -l -m 5
Mar 08 21:24:33.226 WARN poll_device_failed, error: SimpleError { err: "Bad attribute type: UINT64" }
Mar 08 21:24:33.227 DEBG running_command, cmd: aprontest -l -m 6
Mar 08 21:24:33.465 DEBG running_command, cmd: aprontest -l -m 7
Mar 08 21:24:33.666 DEBG running_command, cmd: aprontest -l -m 8
Mar 08 21:24:33.880 DEBG running_command, cmd: aprontest -l -m 11
Mar 08 21:24:34.095 DEBG running_command, cmd: aprontest -l -m 12
Mar 08 21:24:34.304 DEBG running_command, cmd: aprontest -l -m 13
Mar 08 21:24:34.511 DEBG running_command, cmd: aprontest -l -m 15
Mar 08 21:24:37.341 WARN loop_encountered_error, err: Timeout(Elapsed(()))
Mar 08 21:24:42.313 DEBG running_command, cmd: aprontest -l
Mar 08 21:24:42.495 DEBG running_command, cmd: aprontest -l -m 2
Mar 08 21:24:42.678 WARN loop_encountered_error, err: Timeout(Elapsed(()))
Mar 08 21:24:42.725 WARN poll_device_failed, error: SimpleError { err: "Bad attribute type: UINT64" }
Mar 08 21:24:42.726 DEBG running_command, cmd: aprontest -l -m 5
Mar 08 21:24:42.945 WARN poll_device_failed, error: SimpleError { err: "Bad attribute type: UINT64" }
Mar 08 21:24:42.946 DEBG running_command, cmd: aprontest -l -m 6
Mar 08 21:24:42.976 DEBG Publish. Topc = home/wink/6/status
Mar 08 21:24:42.976 DEBG Publish. Pkid = 1, Payload Size = 137
Mar 08 21:24:42.978 DEBG Publish. Topc = home/wink/7/status
Mar 08 21:24:42.979 DEBG Publish. Pkid = 2, Payload Size = 139
Mar 08 21:24:42.981 DEBG Publish. Topc = home/wink/8/status
Mar 08 21:24:42.982 DEBG Publish. Pkid = 3, Payload Size = 16
Mar 08 21:24:42.983 DEBG Publish. Topc = home/wink/11/status
Mar 08 21:24:42.984 DEBG Publish. Pkid = 4, Payload Size = 280
Mar 08 21:24:42.985 DEBG Publish. Topc = home/wink/12/status
Mar 08 21:24:42.986 DEBG Publish. Pkid = 5, Payload Size = 136
Mar 08 21:24:42.986 DEBG Publish. Topc = home/wink/13/status
Mar 08 21:24:42.987 DEBG Publish. Pkid = 6, Payload Size = 137
Mar 08 21:24:42.988 DEBG Publish. Topc = home/wink/15/status
Mar 08 21:24:42.988 DEBG Publish. Pkid = 7, Payload Size = 15
Mar 08 21:24:42.989 DEBG Subscribe. Topics = [Filter = home/wink/+/set, Qos = AtLeastOnce], Pkid = 8
Mar 08 21:24:42.990 DEBG Subscribe. Topics = [Filter = home/wink/+/+/set, Qos = AtLeastOnce], Pkid = 9
Mar 08 21:24:42.991 DEBG Subscribe. Topics = [Filter = homeassistant/status, Qos = AtLeastOnce], Pkid = 10
Mar 08 21:24:42.992 DEBG running_command, cmd: aprontest -l
Mar 08 21:24:43.221 DEBG running_command, cmd: aprontest -l -m 7
Mar 08 21:24:43.234 DEBG Publish. Topc = home/wink/6/status
Mar 08 21:24:43.234 DEBG Publish. Pkid = 11, Payload Size = 137
Mar 08 21:24:43.423 DEBG broadcast_discovery, id: 2
Mar 08 21:24:43.424 DEBG running_command, cmd: aprontest -l -m 2
Mar 08 21:24:43.634 DEBG running_command, cmd: aprontest -l -m 8
Mar 08 21:24:43.638 DEBG Publish. Topc = home/wink/7/status
Mar 08 21:24:43.638 DEBG Publish. Pkid = 12, Payload Size = 139
Mar 08 21:24:44.017 WARN broadcast_discovery_failed, error: SimpleError { err: "Bad attribute type: UINT64" }
`

I removed these with aprontest -d and... look at that.. I now have homeassistant topic showing up:
![image](https://user-images.githubusercontent.com/23066079/110385272-5c42ed00-8024-11eb-9b95-54966a63c457.png)

**Comment by froohoo** [comment]
Thanks Mike for the fix! It is a binary switch sensor for doors / windows. [Listing here](https://www.amazon.com/Quirky-Tripper-Window-Sensor-count/dp/B00P7RURIG). They have been discontinued/unavailable since ~2016 I believe. Not telling you how to live your life, but the install base for this product is probably pretty small at this point, and I don't even use them. But if you are really interested I can power one up and let you know which attribute is the closed/open indicator.
