### ISSUE TITLE
you can include a link to this forum post for Homeseer integration

### ISSUE THREAD

**Issue by dhodgin** [mikekap/wink-mqtt-rs#35]
I recently finished installing this on my wink hub and integrated it with my Homeseer system.

The forum post guide is here: https://forums.homeseer.com/forum/hs4-products/hs4-plugins/lighting-primary-technology-plug-ins-aa/mcsmqtt-michael-mcsharry-aa/1455752-hacking-the-wink-hub-v1-to-work-with-homeseer-via-mscmqtt

If you want to add this to a section in the readme and details some different system that are making use of wink-mqtt-rs, feel free.

You can close this issue once you decide to either add it or just have this issue available for people who search 'using wink hub with homeseer'

**Comment by mikekap** [comment]
Added to the readme - thanks!
